name: Build & Deploy frontend

on:
  push:
    branches: ["main", "dev"]

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # нужно, чтобы пушить в GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set domain based on branch
        id: set-domain
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "DOMAIN=https://nubl.ru" >> $GITHUB_OUTPUT
          else
            echo "DOMAIN=https://nubl.site" >> $GITHUB_OUTPUT
          fi

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VITE_BASE_DOMAIN=${{ steps.set-domain.outputs.DOMAIN }}
            VITE_HOST=""
          tags: |
            ghcr.io/nubl-tech/landing:${{ github.ref_name }}
            ghcr.io/nubl-tech/landing:${{ github.sha }}
            ${{ github.ref_name == 'main' && 'ghcr.io/nubl-tech/landing:latest' || '' }}
